<?php

namespace App\Console\Commands;

use App\Models\EmailNotificationSetting;
use App\Models\MonthlyQuantityReceived;
use App\Models\ReceivedQuantity;
use App\Models\ReceivedQuantityItem;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;

class GenerateMonthlyReceivedReport extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'report:monthly-received-quantities {--month= : The month in YYYY-MM format} {--force : Force regenerate the report even if it already exists}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Generate a monthly report of received quantities';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $monthArg = $this->option('month');
        $force = $this->option('force');
        $today = Carbon::now();

        if (!$monthArg && !$force) {
            $setting = EmailNotificationSetting::monthlyReceivedReportSchedule();
            if (!$setting || !$setting->enabled) {
                $this->info('Monthly received quantities report schedule is disabled or not configured.');
                return 0;
            }
            $config = $setting->config ?? [];
            $dayOfMonth = (int) ($config['day_of_month'] ?? 1);
            $time = $config['time'] ?? '01:00';
            $time = $this->normalizeTime($time);
            $currentTime = $today->format('H:i');
            if ($today->day != $dayOfMonth || $currentTime !== $time) {
                $this->info("Skipping: scheduled for day {$dayOfMonth} at {$time}. Today: {$today->day}, time: {$currentTime}. Use --force to run now.");
                return 0;
            }
        }

        $this->info('Starting monthly received quantities report generation...');

        $isFirstDayOfMonth = $today->day === 1;

        if ($monthArg) {
            // Validate the format
            if (!preg_match('/^\d{4}-\d{2}$/', $monthArg)) {
                $this->error('Invalid month format. Please use YYYY-MM format.');
                return 1;
            }
            $month = $monthArg;
        } else {
            // Default to previous month
            $month = Carbon::now()->subMonth()->format('Y-m');
            
            // Log whether this is running on the first day of the month
            if ($isFirstDayOfMonth) {
                $this->info("Running on the first day of the month: {$today->format('Y-m-d')}");
                $this->info("Automatically generating report for previous month: {$month}");
            } else {
                $this->info("Not running on the first day of the month. Current date: {$today->format('Y-m-d')}");
                $this->info("Still generating report for previous month: {$month}");
            }
        }

        $this->info("Generating report for month: {$month}");

        // Check if report already exists for this month
        $existingReport = MonthlyQuantityReceived::where('month_year', $month)->first();

        if ($existingReport && !$force) {
            $this->warn("A report for {$month} already exists. Use --force to regenerate.");
            return 0;
        }

        // Begin transaction
        DB::beginTransaction();

        try {
            // Delete existing report if force option is used
            if ($existingReport && $force) {
                $this->info("Removing existing report for {$month}...");
                ReceivedQuantityItem::where('parent_id', $existingReport->id)->delete();
                $existingReport->delete();
            }

            // Create a new monthly report
            $report = new MonthlyQuantityReceived();
            $report->month_year = $month;
            $report->generated_by = 'Generated by the System';
            $report->total_quantity = 0; // Initialize total quantity, will update after processing all items
            $report->save();

            $this->info("Created monthly report record with ID: {$report->id}");

            // Start and end of month (inclusive) for consistent date range
            $startDate = Carbon::parse($month . '-01')->startOfMonth()->startOfDay();
            $endDate = Carbon::parse($month . '-01')->endOfMonth()->endOfDay();

            // Get all received quantities for the month (received_at within range only)
            $receivedQuantities = ReceivedQuantity::whereBetween('received_at', [$startDate, $endDate])
                ->with('warehouse')
                ->orderBy('id')
                ->get();

            $this->info("Found {$receivedQuantities->count()} received quantities for {$month}");
            
            // Show unique warehouses being processed
            $uniqueWarehouses = $receivedQuantities->pluck('warehouse_id')->unique();
            $this->info("Processing data for " . $uniqueWarehouses->count() . " warehouse(s): " . $uniqueWarehouses->implode(', '));

            $bar = $this->output->createProgressBar(count($receivedQuantities));
            $bar->start();
            
            $totalQuantity = 0;

            foreach ($receivedQuantities as $receivedQuantity) {
                if (is_null($receivedQuantity->warehouse_id)) {
                    $this->warn("Skipping received quantity ID {$receivedQuantity->id} - no warehouse_id specified");
                    $bar->advance();
                    continue;
                }
                if (is_null($receivedQuantity->product_id)) {
                    $this->warn("Skipping received quantity ID {$receivedQuantity->id} - no product_id specified");
                    $bar->advance();
                    continue;
                }

                // Check if a row for this product_id and warehouse_id already exists in the report
                $item = ReceivedQuantityItem::where('parent_id', $report->id)
                    ->where('product_id', $receivedQuantity->product_id)
                    ->where('warehouse_id', $receivedQuantity->warehouse_id)
                    ->first();
            
                if ($item) {
                    // Update quantity if found
                    $item->quantity += $receivedQuantity->quantity;
                    $item->save();
                } else {
                    // Create new entry if not found
                    ReceivedQuantityItem::create([
                        'parent_id' => $report->id,
                        'product_id' => $receivedQuantity->product_id,
                        'warehouse_id' => $receivedQuantity->warehouse_id,
                        'quantity' => $receivedQuantity->quantity,
                    ]);
                }
            
                // Add to total quantity
                $totalQuantity += $receivedQuantity->quantity;
            
                $bar->advance();
            }
            
            $bar->finish();
            $this->newLine(2);
            
            // Update the monthly report with the total quantity
            $report->total_quantity = $totalQuantity;
            $report->save();
            
            $this->info("Total quantity for this month: {$totalQuantity}");

            // Show summary by warehouse
            $this->showWarehouseSummary($report->id);

            // Commit the transaction
            DB::commit();

            $this->info("\nSuccessfully generated monthly received quantities report for {$month}");
            $this->info("Total items processed: {$receivedQuantities->count()}");

            return 0;
        } catch (\Exception $e) {
            // Rollback the transaction if an error occurs
            DB::rollBack();

            $this->error("An error occurred while generating the report: {$e->getMessage()}");
            $this->error($e->getTraceAsString());

            return 1;
        }
    }

    private function normalizeTime(string $time): string
    {
        if (preg_match('/^\d{1,2}:\d{2}$/', $time)) {
            $parts = explode(':', $time);
            return sprintf('%02d:%02d', (int) $parts[0], (int) ($parts[1] ?? 0));
        }
        return '01:00';
    }

    /**
     * Show summary of received quantities by warehouse
     */
    private function showWarehouseSummary($reportId)
    {
        $this->info("\n" . str_repeat("=", 80));
        $this->info("WAREHOUSE SUMMARY");
        $this->info(str_repeat("=", 80));

        // Get warehouse summary from received quantity items
        $warehouseSummary = ReceivedQuantityItem::where('parent_id', $reportId)
            ->with('warehouse')
            ->selectRaw('warehouse_id, SUM(quantity) as total_quantity, COUNT(*) as product_count')
            ->groupBy('warehouse_id')
            ->get();

        foreach ($warehouseSummary as $summary) {
            $warehouseName = $summary->warehouse ? $summary->warehouse->name : 'Unknown Warehouse';
            $this->info("\nWarehouse: {$warehouseName} (ID: {$summary->warehouse_id})");
            $this->info("  Total Quantity Received: " . number_format($summary->total_quantity));
            $this->info("  Products Count: {$summary->product_count}");
        }

        $this->info("\n" . str_repeat("=", 80));
        $this->info("Total Warehouses: {$warehouseSummary->count()}");
        $this->info("Total Quantity: " . number_format($warehouseSummary->sum('total_quantity')));
        $this->info(str_repeat("=", 80));
    }
}
