<?php

namespace App\Console\Commands;

use App\Models\EmailNotificationSetting;
use App\Models\IssuedQuantity;
use App\Models\IssueQuantityReport;
use App\Models\IssueQuantityItem;
use App\Models\Warehouse;
use Carbon\Carbon;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;

class GenerateIssueQuantityReport extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'report:issue-quantities {--month= : The month in YYYY-MM format} {--force : Force regenerate the report even if it already exists}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Generate a monthly report of issued quantities';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $monthArg = $this->option('month');
        $force = $this->option('force');
        $today = Carbon::now();

        if (!$monthArg && !$force) {
            $setting = EmailNotificationSetting::issueQuantitiesSchedule();
            if (!$setting || !$setting->enabled) {
                $this->info('Issue quantities report schedule is disabled or not configured.');
                return 0;
            }
            $config = $setting->config ?? [];
            $dayOfMonth = (int) ($config['day_of_month'] ?? 1);
            $time = $this->normalizeTime($config['time'] ?? '02:00');
            $currentTime = $today->format('H:i');
            if ($today->day != $dayOfMonth || $currentTime !== $time) {
                return 0;
            }
        }

        $this->info('Starting monthly issued quantities report generation...');

        $isFirstDayOfMonth = $today->day === 1;

        if ($monthArg) {
            // Validate the format
            if (!preg_match('/^\d{4}-\d{2}$/', $monthArg)) {
                $this->error('Invalid month format. Please use YYYY-MM format.');
                return 1;
            }
            $month = $monthArg;
        } else {
            // Default to previous month
            $month = Carbon::now()->subMonth()->format('Y-m');
            
            // Log whether this is running on the first day of the month
            if ($isFirstDayOfMonth) {
                $this->info("Running on the first day of the month: {$today->format('Y-m-d')}");
                $this->info("Automatically generating report for previous month: {$month}");
            } else {
                $this->info("Not running on the first day of the month. Current date: {$today->format('Y-m-d')}");
                $this->info("Still generating report for previous month: {$month}");
            }
        }

        $this->info("Generating report for month: {$month}");

        $warehouses = Warehouse::all();
        if ($warehouses->isEmpty()) {
            $this->error('No warehouses found.');
            return 1;
        }

        foreach ($warehouses as $warehouse) {
            $this->info("Processing Warehouse: {$warehouse->name} (ID: {$warehouse->id})");

            $existingReport = IssueQuantityReport::where('month_year', $month)
                ->where('warehouse_id', $warehouse->id)
                ->first();

            if ($existingReport && !$force) {
                $this->warn("A report for {$month} already exists for {$warehouse->name}. Skipping. Use --force to regenerate.");
                continue;
            }

            DB::beginTransaction();

            try {
                if ($existingReport && $force) {
                    $this->info("Removing existing report for {$month} for {$warehouse->name}...");
                    IssueQuantityItem::where('parent_id', $existingReport->id)->delete();
                    $existingReport->delete();
                }

                $report = new IssueQuantityReport();
                $report->month_year = $month;
                $report->warehouse_id = $warehouse->id;
                $report->generated_by = 'Generated by the System';
                $report->total_quantity = 0;
                $report->save();

                $startDate = Carbon::parse($month . '-01 00:00:00');
                $endDate = Carbon::parse($month . '-01 23:59:59')->endOfMonth();

                $issuedQuantities = IssuedQuantity::whereBetween('issued_date', [$startDate, $endDate])
                    ->where('warehouse_id', $warehouse->id)
                    ->get();

                $this->info("Found {$issuedQuantities->count()} issued quantities for {$warehouse->name}");

                $totalQuantity = 0;
                foreach ($issuedQuantities as $issuedQuantity) {
                    $item = IssueQuantityItem::where('parent_id', $report->id)
                        ->where('product_id', $issuedQuantity->product_id)
                        ->where('warehouse_id', $warehouse->id)
                        ->first();
                
                    if ($item) {
                        $item->quantity += $issuedQuantity->quantity;
                        $item->save();
                    } else {
                        IssueQuantityItem::create([
                            'parent_id' => $report->id,
                            'product_id' => $issuedQuantity->product_id,
                            'warehouse_id' => $warehouse->id,
                            'quantity' => $issuedQuantity->quantity,
                        ]);
                    }
                    $totalQuantity += $issuedQuantity->quantity;
                }
                
                $report->total_quantity = $totalQuantity;
                $report->save();

                DB::commit();
                $this->info("Successfully generated report for {$warehouse->name}. Total quantity: {$totalQuantity}");

            } catch (\Exception $e) {
                DB::rollBack();
                $this->error("Error for {$warehouse->name}: {$e->getMessage()}");
            }
        }

        return 0;
}

    /**
     * Show summary of issued quantities by warehouse
     */
    private function showWarehouseSummary($reportId)
    {
        $this->info("\n" . str_repeat("=", 80));
        $this->info("WAREHOUSE SUMMARY");
        $this->info(str_repeat("=", 80));

        // Get warehouse summary from issue quantity items
        $warehouseSummary = IssueQuantityItem::where('parent_id', $reportId)
            ->with('warehouse')
            ->selectRaw('warehouse_id, SUM(quantity) as total_quantity, COUNT(*) as product_count')
            ->groupBy('warehouse_id')
            ->get();

        foreach ($warehouseSummary as $summary) {
            $warehouseName = $summary->warehouse ? $summary->warehouse->name : 'Unknown Warehouse';
            $this->info("\nWarehouse: {$warehouseName} (ID: {$summary->warehouse_id})");
            $this->info("  Total Quantity Issued: " . number_format($summary->total_quantity));
            $this->info("  Products Count: {$summary->product_count}");
        }

        $this->info("\n" . str_repeat("=", 80));
        $this->info("Total Warehouses: {$warehouseSummary->count()}");
        $this->info("Total Quantity: " . number_format($warehouseSummary->sum('total_quantity')));
        $this->info(str_repeat("=", 80));
    }

    private function normalizeTime(string $time): string
    {
        if (preg_match('/^\d{1,2}:\d{2}$/', $time)) {
            $parts = explode(':', $time);
            return sprintf('%02d:%02d', (int) $parts[0], (int) ($parts[1] ?? 0));
        }
        return '02:00';
    }
}
